{
 "title": "Network QoS Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h2 style='text-align:center; color:#FFFFFF; padding-top:10px;'>☎ VOIP Traffic</h2>"
   }
  },
  {
   "title": "VOIP(EF): Received Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"184\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "VOIP(EF): Received Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "rate(net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"184\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "VOIP(EF): Transmitted Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"184\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "VOIP(EF): Transmitted Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"184\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "<h2 style='text-align:center; color:#FFFFFF; padding-top:10px;'>📽 Video Traffic</h2>"
   }
  },
  {
   "title": "Video(AF41): Received Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"136\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Video(AF41): Received Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"136\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Video(AF41): Transmitted Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"136\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Video(AF41): Transmitted Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"136\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<h2 style='text-align:center; color:#FFFFFF; padding-top:10px;'>🌐  Web Browsing Traffic (HTTP)</h2>"
   }
  },
  {
   "title": "HTTP(AF21): Received Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"72\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "HTTP(AF21): Received Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"72\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "HTTP(AF21): Transmitted Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"72\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "HTTP(AF21): Transmitted Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"72\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 },
   "options": {
    "content": "<h2 style='text-align:center; color:#FFFFFF; padding-top:10px;'>🛢 Database Query Traffic</h2>"
   }
  },
  {
   "title": "DB(CS1): Received Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"32\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "DB(CS1): Received Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "rate(net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"32\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "DB(CS1): Transmitted Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"32\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "DB(CS1): Transmitted Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "rate(net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"32\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 56 },
   "options": {
    "content": "<h2 style='text-align:center; color:#FFFFFF; padding-top:10px;'>⌨️ SSH Traffic</h2>"
   }
  },
  {
   "title": "SSH(CS2): Received Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"64\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "SSH(CS2): Received Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "rate(net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"64\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "SSH(CS2): Transmitted Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"64\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "SSH(CS2): Transmitted Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "rate(net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"64\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 70 },
   "options": {
    "content": "<h2 style='text-align:center; color:#FFFFFF; padding-top:10px;'>✉️ E-MAIL Traffic (SMTP)</h2>"
   }
  },
  {
   "title": "SMTP(CS6): Received Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"192\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "SMTP(CS6): Received Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "rate(net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"192\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "SMTP(CS6): Transmitted Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"192\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "SMTP(CS6): Transmitted Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "rate(net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"192\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 84 },
   "options": {
    "content": "<h2 style='text-align:center; color:#FFFFFF; padding-top:10px;'>📂 Bulk File Transfer Traffic (FTP)</h2>"
   }
  },
  {
   "title": "FTP(AF11): Received Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"40\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "FTP(AF11): Received Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "rate(net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"40\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "FTP(AF11): Transmitted Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"40\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "FTP(AF11): Transmitted Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "rate(net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"40\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 98 },
   "options": {
    "content": "<h2 style='text-align:center; color:#FFFFFF; padding-top:10px;'>📦 Other Traffic</h2>"
   }
  },
  {
   "title": "Other: Received Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"0\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Other: Received Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "rate(net_rx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"0\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Other: Transmitted Total Packets - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"0\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Other: Transmitted Packet Throughput (Packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "rate(net_tx_tos_packets{job=\"hosts-passive-metrics\", interface!=\"lo\", interface!=\"eth0\", tos=\"0\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  }
 ]
}