global:
  scrape_interval: 20s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
      
  - job_name: 'hosts-passive-metrics'
    static_configs:
      - targets: ['172.17.0.2:8000']
        labels:
          alias: d1
      - targets: ['172.17.0.3:8000']
        labels:
          alias: d2
      - targets: ['172.17.0.4:8000']
        labels:
          alias: d3
      - targets: ['172.17.0.5:8000']
        labels:
          alias: d4
      - targets: ['172.17.0.6:8000']
        labels:
          alias: d5
      
  - job_name: 'd1-active-metrics'
    metrics_path: /probe
    params:
      module: [icmp]  # Change to relevent module (icmp, tcp_connect, dns, etc.)
    static_configs:
      - targets:
          - 192.168.0.1 
          - 192.168.0.2 
          - 192.168.0.3 
          - 192.168.0.4
          - 192.168.0.5
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.0.2:9115  # IP or DNS of Blackbox Exporter
        
  - job_name: 'd2-active-metrics'
    metrics_path: /probe
    params:
      module: [icmp]  # Change to relevent module (icmp, tcp_connect, dns, etc.)
    static_configs:
      - targets:
          - 192.168.0.1 
          - 192.168.0.2 
          - 192.168.0.3 
          - 192.168.0.4 
          - 192.168.0.5
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.0.3:9115  # IP or DNS of Blackbox Exporter

  - job_name: 'd3-active-metrics'
    metrics_path: /probe
    params:
      module: [icmp]  # Change to relevent module (icmp, tcp_connect, dns, etc.)
    static_configs:
      - targets:
          - 192.168.0.1 
          - 192.168.0.2 
          - 192.168.0.3 
          - 192.168.0.4   
          - 192.168.0.5
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.0.4:9115  # IP or DNS of Blackbox Exporter
        
  - job_name: 'd4-active-metrics'
    metrics_path: /probe
    params:
      module: [icmp]  # Change to relevent module (icmp, tcp_connect, dns, etc.)
    static_configs:
      - targets:
          - 192.168.0.1 
          - 192.168.0.2 
          - 192.168.0.3 
          - 192.168.0.4  
          - 192.168.0.5
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.0.5:9115  # IP or DNS of Blackbox Exporter

  - job_name: 'd5-active-metrics'
    metrics_path: /probe
    params:
      module: [icmp]  # Change to relevent module (icmp, tcp_connect, dns, etc.)
    static_configs:
      - targets:
          - 192.168.0.1 
          - 192.168.0.2 
          - 192.168.0.3 
          - 192.168.0.4 
          - 192.168.0.5
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.0.6:9115  # IP or DNS of Blackbox Exporter
